build:
  nodes:
    coverage:
      tests:
        before:
          - command: npm start
          background: true
        override:
          - command: npm test
        coverage:
          file: coverage/clover.xml
          format: clover
   # before:
   #    - command: npm start
   #      background: true
   #  override:
   #    - command: npm test
  # tests:
  #   before:
  #     - command: npm run serve
  #       background: true
  #   override:
  #     - command: npm run test
